#!/bin/bash

# Checking for root
if [[ $EUID -ne 0 ]]; then
   echo "Run nitonltc with sudo."
   exit 1
fi

# Adding some color options.

export COLOR_NC='\e[0m' # No Color
export COLOR_WHITE='\e[1;37m'
export COLOR_BLACK='\e[0;30m'
export COLOR_BLUE='\e[0;34m'
export COLOR_LIGHT_BLUE='\e[1;34m'
export COLOR_GREEN='\e[0;32m'
export COLOR_LIGHT_GREEN='\e[1;32m'
export COLOR_CYAN='\e[0;36m'
export COLOR_LIGHT_CYAN='\e[1;36m'
export COLOR_RED='\e[0;31m'
export COLOR_LIGHT_RED='\e[1;31m'
export COLOR_PURPLE='\e[0;35m'
export COLOR_LIGHT_PURPLE='\e[1;35m'
export COLOR_BROWN='\e[0;33m'
export COLOR_YELLOW='\e[1;33m'
export COLOR_GRAY='\e[0;30m'
export COLOR_LIGHT_GRAY='\e[0;37m'


if [[ $1 == "install" ]]; then

   # Check for packages and install if not installed.

   echo "Installing packages..."

   user_logged_in=$(logname)

   # Install figlet if not installed.
   command -v figlet >/dev/null 2>&1 || {
      sudo apt-get install -y figlet > /dev/null 2>&1 && echo -e "[${COLOR_LIGHT_GREEN}+${COLOR_NC}] FIGlet installed using apt-get..";
   }

   # Install git if not installed.
   command -v git >/dev/null 2>&1 || {
      sudo apt-get install -y git > /dev/null 2>&1 && echo -e "[${COLOR_LIGHT_GREEN}+${COLOR_NC}] Git installed using apt-get..";
   }

   # Install python if not installed.
   command -v python >/dev/null 2>&1 || {
      sudo apt-get install -y python > /dev/null 2>&1 && echo -e "[${COLOR_LIGHT_GREEN}+${COLOR_NC}] Python installed using apt-get..";
   }

   # Install ruby if not installed.
   command -v ruby >/dev/null 2>&1 || {
      sudo apt-get install -y ruby > /dev/null 2>&1 && echo -e "[${COLOR_LIGHT_GREEN}+${COLOR_NC}] Ruby installed using apt-get..";
   }

   # Install python-pip if not installed.
   command -v python-pip >/dev/null 2>&1 || {
      sudo apt-get install -y python-pip > /dev/null 2>&1 && echo -e "[${COLOR_LIGHT_GREEN}+${COLOR_NC}] Pip installed using apt-get..";
   }

   mkdir -p /home/$user_logged_in/nitonltc > /dev/null 2>&1 && echo -e "[${COLOR_LIGHT_GREEN}+${COLOR_NC}] Creating application folder..";
   cd /home/$user_logged_in/nitonltc


   echo -e "[${COLOR_LIGHT_BLUE}i${COLOR_NC}] Downloading busyloop/lolcat"
   # Installing lolcat
   wget https://github.com/busyloop/lolcat/archive/master.zip >/dev/null 2>&1
   unzip master.zip >/dev/null 2>&1
   cd lolcat-master/bin/ >/dev/null 2>&1

   echo -e "[${COLOR_LIGHT_GREEN}+${COLOR_NC}] Installing busyloop/lolcat"

   gem install lolcat >/dev/null 2>&1

   echo "Step 1 of 3 completed..." | lolcat -a -d 50

   sleep 2

   cd /home/$user_logged_in/nitonltc

   echo -e "[${COLOR_LIGHT_GREEN}+${COLOR_NC}] System update..." && sudo apt-get update -y >/dev/null 2>&1
   echo -e "[${COLOR_LIGHT_GREEN}+${COLOR_NC}] System upgrade.." && sudo apt-get upgrade -y >/dev/null 2>&1


   echo -e "[${COLOR_LIGHT_GREEN}+${COLOR_NC}] Installing bot application.."

   sudo rm -rf "/home/$user_logged_in/nitonltc/master.zip"
   sudo rm -rf "/home/$user_logged_in/nitonltc/lolcat-master"

   sleep 1
   echo -e "[${COLOR_LIGHT_BLUE}i${COLOR_NC}] Downloading NitonLTC..."
   wget https://github.com/nitonbots/nitonltc/archive/master.zip >/dev/null 2>&1
   unzip master.zip >/dev/null 2>&1
   cd nitonltc-master/ >/dev/null 2>&1

   pip install -r requirements.txt >/dev/null 2>&1 && echo -e "[${COLOR_LIGHT_GREEN}+${COLOR_NC}] Installing bot application .."
   echo "Step 2 of 3 completed..." | lolcat -a -d 50

   sleep 2
   exit 1;

fi

echo "Run the installer by running \"sudo ./nitonltc install\""
